"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetaTxReceiver__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MetaTxReceiver__factory_1 = require("./MetaTxReceiver__factory");
Object.defineProperty(exports, "MetaTxReceiver__factory", { enumerable: true, get: function () { return MetaTxReceiver__factory_1.MetaTxReceiver__factory; } });
