"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OracleConsumerContract__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var OracleConsumerContract__factory_1 = require("./OracleConsumerContract__factory");
Object.defineProperty(exports, "OracleConsumerContract__factory", { enumerable: true, get: function () { return OracleConsumerContract__factory_1.OracleConsumerContract__factory; } });
